### ISSUE TITLE
RPKI testbed issue: "key doesn't match TAL. No valid trust anchor for TAL testbed"

### ISSUE THREAD

**Issue by villagejames** [NLnetLabs/krill#638] opened 2021-08-17 13:40 UTC
Hello,

I'm trying to use the rpki testbed https://testbed.rpki.nlnetlabs.nl/index.html#/testbed. The test using krill has been a sucess.

However the .tal archive located at https://testbed.rpki.nlnetlabs.nl/testbed.tal accuses error when using with routinator validator.

The output when executing routinator as follows:

#routinator -vv vrps
Trust anchor https://testbed.rpki.nlnetlabs.nl/ta/ta.cer: key doesn't match TAL.
No valid trust anchor for TAL testbed

#routinator -vv --disable-rrdp vrps
rsync://testbed.rpki.nlnetlabs.nl/ta/: Running command Command { std: "rsync" "contimeout=10" "--max-size=20000000" "-rltz" "--delete" "rsync://testbed.rpki.nlnetlabs.nl/ta/" "/root/.rpki-cache/repository/rsync/testbed.rpki.nlnetlabs.nl/ta/", kill_on_drop: false }
rsync://testbed.rpki.nlnetlabs.nl/ta/ta.cer: not found in local repository
No valid trust anchor for TAL testbed

Is there a way to accept the .tal archive? I've tried with --allow-dubious-hosts but even with the option it doesn't work.

**Comment by ximon18** [comment] 2021-08-17 14:27
Hi @villagejames,

Sorry for the inconvenience. It should be working now:

```
$ routinator -V
Routinator 0.9.0
$ routinator init --accept-arin-rpa
$ rm ~/.rpki-cache/tals/*
$ cd ~/.rpki-cache/tals/
$ wget -q https://testbed.rpki.nlnetlabs.nl/testbed.tal
$ routinator -vv --fresh vrps
Found valid trust anchor https://testbed.rpki.nlnetlabs.nl/ta/ta.cer. Processing.
RRDP https://testbed.rpki.nlnetlabs.nl/rrdp/notification.xml: Tree has 0 entries.
RRDP https://testbed.rpki.nlnetlabs.nl/rrdp/notification.xml: updating from snapshot.
RRDP https://testbed.rpki.nlnetlabs.nl/rrdp/notification.xml: snapshot update completed.
...
```

One remaining issue is that `routinator init --tal nlnetlabs-testbed` will install the old no longer correct TAL. We'll need to update the testbed TAL in the next Routinator release.

Ximon

**Comment by ximon18** [comment] 2021-08-17 14:31
I have created https://github.com/NLnetLabs/routinator/issues/636 for the Routinator issue.

**Comment by ximon18** [comment] 2021-08-17 14:37
FYI the root cause of this issue was https://lists.nlnetlabs.nl/pipermail/rpki/2021-August/000306.html. As part of the reset we neglected to copy the TAL to be served from the `/testbed.tal` location and so the old TAL continued to be served. We'll look into using just a single TAL location when we upgrade the testbed to the upcoming Krill 0.9.2.

**Comment by ximon18** [comment] 2021-09-23 10:10
Closing as there's nothing more to be done for the Krill testbed regarding this issue and no further issues have been observed/reported.

**Closed by ximon18** 2021-09-23 10:10 UTC
