### ISSUE TITLE
ARM Support for Docker Images

### ISSUE THREAD

**Issue by ericparton** [NLnetLabs/krill#764] opened 2022-01-26 22:05 UTC
Hello,

Would it be possible to produce Krill Docker images that have support for ARM architectures?  With the proliferation of ARM-based MacBook laptops and ARM-based virtual machines offered by cloud providers, ARM architectures are becoming more popular. 

Thanks

**Comment by ximon18** [comment] 2022-01-27 22:50
Good evening @ericparton,

Apologies for the delayed response, I was busy investigating the various options for doing this.

I have worked out a way to do this which builds on the recent work done to create DEB packages for ARM (specifically for ARMv7/armhf tested on a Raspberry Pi 4b, and ARM64/aarch64 tested on a Pine64). This would result in Docker images that like our current Docker images use an Alpine base image and use [musl libc](https://musl.libc.org/) instead of glibc, and just like the ARM DEB packages would use statically linked OpenSSL.

Would this work for you? Which ARM architecture and operating system are you interested in using this on?

It will take me a little while to work out how best to add this in to our existing GitHub Actions packaging workflows as currently the cross compilation is done in the `pkg` workflow but the Docker image building is done in the `pkg-docker.yml` workflow, and currently they trigger slightly differently so can't easily be merged, and if not merged then one would have to wait for and take binaries built by the other (e.g. using GitHub Action `dawidd6/action-download-artifact@2`), and the Docker workflow needs to be extended to do cross-target building (e.g. using `docker/setup-qemu-action@v1` and `docker/setup-buildx-action@v1`).

If you'd like to test an ARM Krill Docker image I have a prototype setup I can use to build a one-off image, I just need to know which architecture to target, preferably I need to know both of the following:

- QEmu supported target, for ARM that is either `linux/arm/v7` or `linux/arm/v6` (taken from the output of the `docker/setup-qemu-action@v1` GitHub Action)
- Cargo cross supported target name, one of the ARM `target` values listed here: https://github.com/cross-rs/cross#supported-targets

Thanks,

Ximon

**Comment by ericparton** [comment] 2022-02-01 21:41
Thanks for taking a look at this. Just to give you some more context, our engineers use MacBooks to write software and we use the Krill Docker image during the development and testing process of our RPKI software. 

As of last November, Apple only sells their ARM based MacBooks, so we've been going through all the software that our engineers use and making sure that it works on an ARM based MacBook before we start purchasing more of the new MacBooks for general use throughout the organization.

I'd be more than happy to test out an ARM Krill docker image. Another department currently has the M1 MacBook that we've been using for testing, but I should be able to get it back in another week or so. 

The QEMU support target for the M1 Macs is ``linux/arm64`` and I believe that the cargo cross supported target name is ``aarch64-unknown-linux-gnu``.

Thanks,
Eric

**Comment by AlexanderBand** [comment] 2022-02-02 14:07
I'm well aware of the advantages of Docker but while we get ARM support sorted, I'd like to note that I have very good experiences running Krill and Routinator from my M1 Mac using Cargo, Rust's package manager. It compiles super fast and running is effortless. Is this something you've considered/tried? https://krill.docs.nlnetlabs.nl/en/stable/install-and-run.html#installing-with-cargo

**Comment by ericparton** [comment] 2022-02-02 19:40
Thanks, that's a good suggestion. I'll see if I can get that up and running when I have access to the M1 Mac again.

**Comment by ximon18** [comment] 2022-02-11 15:03
Hi @ericparton,

In https://github.com/NLnetLabs/krill/pull/773 I have prepared Docker ARM support, but not for Macs but rather based on our existing work for Raspberry Pi and Rock64.

Which CPU architecture were you wanting support for?

Ximon

**Comment by ericparton** [comment] 2022-02-14 15:29
From what I understand, the M1 macs also require ARM64/aarch64, so you should be good there.

**Comment by ericparton** [comment] 2022-07-28 19:16
@ximon18 I just wanted to circle back around to this and let you know that we've been using the `ximoneighteen/krill` docker image from #773 on an experimental basis on our evaluation M1 MacBook Pro and it's been working perfectly as far as we can tell.

**Closed** 2022-08-09 20:34 UTC
Labels: docker, github actions, packaging, armv7

**Comment by ximon18** [comment] 2022-08-10 09:27
Hi @ericparton,

Support for building Krill Docker images for multiple CPU architectures and offering them as a [Docker `multi-arch` image](https://docs.docker.com/desktop/multi-arch/) has been merged to the `main` branch.

Currently this means that the `nlnetlabs/krill:unstable` image is available since last night for multiple CPU architectures as shown on the [Krill Docker Hub page](https://hub.docker.com/r/nlnetlabs/krill/tags):

![image](https://user-images.githubusercontent.com/3304436/183865890-f392cdf8-f59c-4150-ba0c-15f47956c52f.png)

From this point on any official tagged releases of Krill (i.e. `nlnetlabs/krill:vXXX` and `nlnetlabs/krill:latest`) or updates to the Krill `main` branch (i.e. the `nlnetlabs/krill:unstable` image) will automatically result in updates to the mutli-arch images being published to Docker Hub. 

We have NOT provided muti-arch images retrospectively for existing Krill releases.

If you have any feedback or can just confirm that it works for you that would be great to hear.

Ximon

**Comment by ericparton** [comment] 2022-08-10 17:57
Hey @ximon18,

I switched over to the new arm64 `nlnetlabs/krill:unstable` image from the arm64 `ximoneighteen/krill` image that you published a few months ago and I was able to log in and create a CA, but after that all I see is a blank screen. It also looks like there are some errors in the logs and in the developer console:

<img width="1504" alt="Screen Shot 2022-08-10 at 10 29 05 AM" src="https://user-images.githubusercontent.com/13722178/183979423-6b233b64-de81-4328-a6d0-74bf96c70ec2.png">

```
2022-08-10 17:54:40 [DEBUG] [krill::daemon::http::server] Server Error: No repository configured for CA
2022-08-10 17:54:40 [WARN] [krill::daemon::http::server] HTTP 400: No repository configured for CA
2022-08-10 17:54:40 [DEBUG] [krill::daemon::http::server] GET /api/v1/cas/ARINL/repo 400 Bad Request
```

If I delete the krill data directory and switch back to the older `ximoneighteen/krill` image everything seems to work again. The working image is based off of `v0.9.5-dev` instead of `0.10.0-rc2`, but I don't know if that makes a difference here.

**Comment by ximon18** [comment] 2022-08-10 18:01
Hi @ericparton,

Thanks for the feedback!

There is at least one known bug  (#868) in v0.10.0-rc2 and the current main branch which rc3 will fix.

We will investigate and see if you have hit that or found another or if something else is going on.

Cheers,

Ximon

**Comment by ximon18** [comment] 2022-08-11 12:13
Hi @ericparton,

We can reproduce the issue, it occurs in all builds of Krill, not just ARM Docker. We have automated UI tests that would catch this but they are fragile and currently disabled. All other tests use the API which is working fine, this is an issue only with the web UI.

We'll fix this and issue a new release.

Ximon

**Comment by ericparton** [comment] 2022-08-11 20:28
> Hi @ericparton,
> 
> We can reproduce the issue, it occurs in all builds of Krill, not just ARM Docker. We have automated UI tests that would catch this but they are fragile and currently disabled. All other tests use the API which is working fine, this is an issue only with the web UI.
> 
> We'll fix this and issue a new release.
> 
> Ximon

Thanks for looking into this!
