### ISSUE TITLE
Incorrect AIA in certificate issued by TA

### ISSUE THREAD

**Issue by tomhrr** [NLnetLabs/krill#409] opened 2021-01-26 23:24 UTC
The 0/0 certificate issued by the TA (with SKI 1040FA57F99F4B3DE2626F6EE1C56664CB81D2C8) has an incorrect AIA pointer.  It is rsync://testbed.rpki.nlnetlabs.nl/repo/ta/ta.cer, but should be rsync://testbed.rpki.nlnetlabs.nl/ta/ta.cer.  This came up when testing our RTA validator (https://github.com/APNIC-net/rpki-rta-demo), because it uses AIAs to find the certificates that it needs for validation.

**Comment by timbru** [comment] 2021-01-28 10:42
Right, the TA support is indeed a bit hit and miss - because we originally intended this for local testing use.

That said.. Krill now derives the AIA uri from the base rsync uri set in the config. I will add an explicit (hidden) entry in the config file for this, so you can change it to point to another rsync module. Note that you will still have to download the ta.cer file manually and copy it over to your rsync source folder.

The TA.cer is treated a bit differently because it's not part of the set published by the TA. So, this why we need separate locations and may have to copy things over by hand. If we build better TA support in future (if people want to run Krill as a proper TA in production) then we will address this.

**Comment by timbru** [comment] 2021-01-28 11:17
Ok, I should have looked better - of course you are not using your own testbed, but our test bed for this.. I have a fix for the 0.8.2 code base that we can try. However, it means that CAs will have to re-register. Will keep you posted on the progress.

**Comment by timbru** [comment] 2021-01-28 15:35
This should be fixed now. I was able to do some creative editing of json on our testbed server. Not recommended for people to try at home.

I will leave this issue open to ensure that we include a fix/documentation in the 0.9 release.

**Comment by tomhrr** [comment] 2021-01-31 21:37
Thanks, AIA in the testbed looks good and RTA validation is working as expected.

**Comment by ximon18** [comment] 2021-09-23 11:07
Closing as it was confirmed to be fixed and there haven't been any observed or reported issues since then.

**Closed by ximon18** 2021-09-23 11:07 UTC
