### ISSUE TITLE
Update Krill to Support Latest ASPA Draft

### ISSUE THREAD

**Issue by yoitszigi** [NLnetLabs/krill#1135] opened 2023-10-10 12:50 UTC
Hello,

I noticed that the ASPA draft was updated in August 2023, and it now merges V4 and V6 providers, eliminating the separation between the two. Given these updates, can Krill be updated to align with the latest ASPA draft?

Reference: [ASPA Verification Draft #16](https://datatracker.ietf.org/doc/draft-ietf-sidrops-aspa-verification/16/)

**Comment by timbru** [comment] 2023-10-10 12:54
Hi,

In short: Yes.

This is a duplicate of issue #1080. It is on the top of our to-do list *after* the coming 0.14.0 release.

**Closed by timbru** 2023-10-10 12:54 UTC
