### ISSUE TITLE
Missing argument

### ISSUE THREAD

**Issue by dev-gto** [NLnetLabs/krill#145] opened 2019-11-22 14:01 UTC
I was trying to switch back from a remote repository, and I got this strange message
```
krillc repo update embedded --ca nicbr_ca --server https://nir.krill.docker:3000/ --token somethingElse
Missing argument: --server, alternatively you may use env var: KRILL_CLI_SERVER
```
Only when I set KRILL_CLI_SERVER, KRILL_CLI_TOKEN and KRILL_CLI_MY_CA it works.

While using `update rfc8183` this behavior does not happen.

**Comment by timbru** [comment] 2019-11-28 13:03
This is very strange. I cannot reproduce the issue, and looking at the code I cannot see how this can occur either. The 'general arguments' are parsed in both cases, using the same function.

Is this still an issue? If not I propose that we close this and re-open when it can be reproduced.

**Comment by timbru** [comment] 2019-12-02 08:59
Closing because I cannot reproduce the issue. Feel free to re-open in case it happens again.

**Closed by timbru** 2019-12-02 08:59 UTC
