### ISSUE TITLE
Clean up old keys

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill#728] opened 2021-11-19 14:43 UTC
Keys are currently not cleaned up if a key roll is completed, or a CA is removed. This could lead to issues when using an HSM with limited space for keys.

Note: check whether `destroy_key` should be idempotent - or errors ignored in case the CA wants to clean up a key which is already removed.

**Comment by ximon18** [comment] 2021-11-22 21:42
Related: #569

**Comment by ximon18** [comment] 2022-09-06 09:03
Closing as a duplicate of #106.

**Closed by ximon18** 2022-09-06 09:03 UTC
Labels: hsm
