### ISSUE TITLE
Chrome 80 refuses to show the Krill v0.5.0 Lagosta UI

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill#210] opened 2020-02-25 14:05 UTC
**Environment:**
- Krill version: `nlnetlabs/krill:v0.5.0` (Docker image)
- O/S: Ubuntu 20.04
- Browser: Google Chrome 80.0.3987.106

Note: The same issue does **NOT** exist with Firefox 73.0 (64-bit) on the same O/S.

**Krill Command(s):**
Based on the [documentation](https://rpki.readthedocs.io/en/latest/krill/docker.html#fetching-and-running-krill):
```
docker run --rm --name krill -p 127.0.0.1:3000:3000 \
    -e KRILL_LOG_LEVEL=info \
    -e KRILL_FQDN=rpki.example.net \
    -e KRILL_AUTH_TOKEN=xxx \
    -e TZ=Europe/Amsterdam \
    -v krill_data:/var/krill/data/ \
    -v /tmp/krill_rsync/:/var/krill/data/repo/rsync/ \
    nlnetlabs/krill:v0.5.0
```

**Unexpected Behaviour:**

Yes the certificate is self-signed, but I am surprised that I cannot accept the certificate anyway. This is probably a Google Chrome security feature but just in case it is something about the Krill self-signed certificate I am raising this issue.

![image](https://user-images.githubusercontent.com/3304436/75254021-f7816f80-57df-11ea-83c1-7bdd18ae5c6b.png)

Thanks,

Ximon

**Comment by timbru** [comment] 2020-06-25 14:06
Cannot reproduce (chrome 83). Closing for now.

**Closed by timbru** 2020-06-25 14:06 UTC
Labels: docker, invalid
