### ISSUE TITLE
How to run my own krill testbed in docker？

### ISSUE THREAD

**Issue by pluschen-stack** [NLnetLabs/krill#1011] opened 2023-02-14 18:17 UTC
I am reading [Running with Docker](https://krill.docs.nlnetlabs.nl/en/stable/docker.html) and [Running a Krill Test Environment](https://krill.docs.nlnetlabs.nl/en/stable/testbed.html).
I want to build my own test environment with krill and routinator in docker.
Here is the my krill.conf
```toml
admin_token = "krillTestBed"
data_dir = "/var/lib/krill/data/"
log_type = "syslog"
ip = "172.17.0.2"
service_uri = "https://172.17.0.2:3000/"
bgp_risdumps_enabled = false

[testbed]
rrdp_base_uri = "https://172.17.0.2:3000/rrdp/"
rsync_jail = "rsync://172.17.0.2:3000/repo/"
ta_uri = "https://172.17.0.2:3000/ta/ta.cer"
ta_aia = "rsync://172.17.0.2:3000/ta/ta.cer"
```
So I run the command below.
```bash
$ docker run -d --name krill \
 -v /home/ubuntu/Desktop/krill.conf:/var/krill/data/krill.conf \
 nlnetlabs/krill
```
however the krill excited.
```bash
$ docker ps -a
CONTAINER ID   IMAGE             COMMAND                  CREATED         STATUS                    PORTS     NAMES
1c9e09501c72   nlnetlabs/krill   "/sbin/tini -- /opt/…"   4 seconds ago   Exited (1) 1 second ago             krill
```
and when i restart krill and try to input some command,it show me http client error. 
```bash
$ docker restart krill
$ docker exec krill krillc list --token krillTestBed
Http client error: Issue accessing URI: https://localhost:3000/api/v1/cas, error: error sending request for url (https://localhost:3000/api/v1/cas): error trying to connect: tcp connect error: Address not available (os error 99)
```
May i ask why it can't do some krill command?

**Comment by ximon18** [comment] 2023-02-15 11:07
Hi @pluschen-stack,

Thanks for trying out Krill, and I'm sorry that you weren't able to get it to work as you expected.

I'll start with the `krillc` error and go on from there:

## Why is `krillc` unable to connect?

```
$ docker exec krill krillc list --token krillTestBed
Http client error: Issue accessing URI: https://localhost:3000/api/v1/cas, error: error sending request for url (https://localhost:3000/api/v1/cas): error trying to connect: tcp connect error: Address not available (os error 99)
```

The error here is as stated, though perhaps it could be more clearer and/or more helpful: `krillc` is unable to connect to Krill at https://localhost:3000/ because it failed at the TCP layer to connect because there is no process listening on the given address ("localhost").

This is because:

  - a) `krillc` assumes by default that Krill is reachable on https://localhost:3000/, and
  - b) Krill listens on the network interface specified by the `ip` address setting given in `krill.conf` which in your case is not "localhost".

## How to configure `krillc` to connect to Krill at a non-default location

One can override the `krillc` default location at which it expects to be able to connect to Krill by passing `-s` (aka `--server`) to `krillc` with value https://172.17.0.2:3000/. However as we will see below in a moment this isn't going to be enough in this case.

## How to configure Krill to listen on the desired network interfaces

By default the Krill Docker image uses a `krill.conf` that contains `ip = "0.0.0.0"` which differs to the value you used for this setting.

By using `ip = "0.0.0.0"` causes Krill to listen on ALL interfaces for IPv4 connections, which includes the "localhost" interface. In your case by setting `ip = "172.17.0.2"` you caused Krill to listen ONLY on that particular IPv4 address and NOT on the  "localhost" interface.

You can see the defaults that the Krill Docker image uses by just running `docker run --rm nlnetlabs/krill`:

```
$  docker run --rm nlnetlabs/krill
docker-krill: Securing Krill daemon with token 28143116-2d05-4edd-a8a6-8d34bc9ec06c
docker-krill: Configuring /var/krill/data/krill.conf ..
docker-krill: Dumping /var/krill/data/krill.conf config file
ip = "0.0.0.0"
port = 3000
data_dir = "/var/krill/data"
log_type = "stderr"
log_level   = "warn" # DO NOT TOUCH, THIS LINE IS MANAGED BY DOCKER KRILL
docker-krill: End of dump
```

Note that depending on your Docker networking setup the network the container is running in may not be 172.17.0.x and/or the container may not receive IP address 172.17.0.2.

As we will see below an even better default to use is `ip = "::"` (though this may be because on my Docker setup I have `"ipv6": true" set in my `/etc/docker/daemon.json` file).

## Why is the Krill container exiting instead of continuing to run as a deamon in the background?

The biggest issue here isn't actually that `krillc` can't connect, but that the `krill` container exits rather than continues running as it should. You can't see why because you altered the logging settings.

By default, as shown above, `krill.conf` as used by the Krill Docker image sets `log_type = "stderr"` but in your example you set it to `log_type = "syslog"`. Typically Docker containers do not have a syslog daemon running inside them as the Docker way is to run only a single process inside each container. While one _can_ setup a syslog daemon inside a Docker container it is not recommended and running multiple processes quickly leads to problems with signal propagation and zombie processes not being reaped. This is not a Krill issue, this is a Docker thing. So in your case the Krill logs have no syslog daemon inside the container to receive them and are lost.

If we fix this issue by setting `log_type = "stderr"`, and making it even easier for ourselves to test by NOT passing `-d` to `docker run`, then we can see the Krill logs on the console when invoking `docker run` and can see what the problem is:

```
2023-02-15 10:16:56 [ERROR] Krill failed to start: CA 'testbed' could not sync with parent 'ta', for resource class '0', error: Invalid CSR received: MUST use hostnames in URIs for certificate requests.
```

Ahha! Your use of 172.17.0.2 in `xxx_uri` and `xxx_aia` settings within `krill.conf` is not allowed.

## Using a hostname instead of an IP address

To set them instead to a hostname one must know a hostname that is resolvable to the IP address on which Krill is listening. Unfortunately a Docker containers hostname defaults to the generated ID of the Docker container which we can't know in advance. We can however set the hostname when running the container, so:

1. Replace occurrences of 172.17.0.2 in `krill.conf` with `krill`.
2. Pass `--hostname krill` to `docker run`.

Then we get:

```
❯ docker run --rm --name krill -v /tmp/krill.conf:/var/krill/data/krill.conf --hostname krill nlnetlabs/krill
docker-krill: Securing Krill daemon with token e61e1bee-132c-4aa8-8d3a-a5c856440be6
docker-krill: Configuring /var/krill/data/krill.conf ..
docker-krill: Warning! Cannot write to /var/krill/data/krill.conf. You can ignore this warning if you mounted your own config file over /var/krill/data/krill.conf.
2023-02-15 10:51:39 [INFO] Krill uses configuration file: /var/krill/data/krill.conf
2023-02-15 10:51:39 [INFO] Scanning for not yet mapped OpenSSL signer keys in /var/lib/krill/data/keys to record in the signer store
2023-02-15 10:51:39 [INFO] Configuring signer 'Default OpenSSL signer' (type: OpenSSL, default: true, one_off: true)
2023-02-15 10:51:39 [INFO] Recorded 0 key identifiers in the signer store
2023-02-15 10:51:39 [INFO] Starting Krill v0.12.1
2023-02-15 10:51:39 [INFO] Krill uses service uri: https://krill:3000/
2023-02-15 10:51:39 [INFO] Enabling TESTBED mode - ONLY USE THIS FOR TESTING AND TRAINING!
2023-02-15 10:51:39 [INFO] Configuring signer 'Default OpenSSL signer' (type: OpenSSL, default: true, one_off: true)
2023-02-15 10:51:39 [INFO] Cache for CAs has been warmed.
2023-02-15 10:51:39 [INFO] Initializing repository
2023-02-15 10:51:39 [INFO] Signer 'Default OpenSSL signer' is ready for use
2023-02-15 10:51:39 [INFO] Creating embedded Trust Anchor
2023-02-15 10:51:39 [INFO] Sending command to publisher '0', version: 1: id '0' version 'any' details 'Added publisher 'ta''
2023-02-15 10:51:39 [INFO] CA 'ta' updated repository. Service URI will be: https://krill:3000/rfc8181/ta/
2023-02-15 10:51:39 [INFO] Created Trust Anchor
2023-02-15 10:51:39 [INFO] Received certificate for CA 'ta' under RC '0', with resources: 'asn: 'AS0-AS4294967295', ipv4: '0.0.0.0/0', ipv6: '::/0'' valid until: '2123-02-15T10:51:39+00:00'
2023-02-15 10:51:39 [INFO] Creating embedded Testbed CA
2023-02-15 10:51:39 [INFO] Sending command to publisher '0', version: 2: id '0' version 'any' details 'Added publisher 'testbed''
2023-02-15 10:51:39 [INFO] CA 'testbed' updated repository. Service URI will be: https://krill:3000/rfc8181/testbed/
2023-02-15 10:51:39 [INFO] CA 'ta' process add child request: handle 'testbed' resources 'asn: 'AS0-AS4294967295', ipv4: '0.0.0.0/0', ipv6: '::/0''
2023-02-15 10:51:39 [INFO] CA 'ta' added child 'testbed' with resources 'asn: 'AS0-AS4294967295', ipv4: '0.0.0.0/0', ipv6: '::/0''
2023-02-15 10:51:39 [INFO] CA 'testbed' added parent 'ta'
2023-02-15 10:51:39 [INFO] CA 'testbed' received entitlement under parent 'ta', created resource class '0' and made certificate request
2023-02-15 10:51:39 [INFO] CA 'ta' issued certificate '65D227D09DE68CC1D6CF82C671B21E75C9D6CB1B.cer' to child 'testbed'
2023-02-15 10:51:39 [INFO] Received certificate for CA 'testbed' under RC '0', with resources: 'asn: 'AS0-AS4294967295', ipv4: '0.0.0.0/0', ipv6: '::/0'' valid until: '2024-02-14T10:51:39+00:00'
2023-02-15 10:51:40 [INFO] Synchronize CA 'testbed' with its parent 'ta'
2023-02-15 10:51:42 [INFO] Synchronize CA 'testbed' with its parent 'ta'
2023-02-15 10:51:42 [INFO] Synchronize CA 'ta' with its parent 'ta'
```

Ahha, that looks better!

## Why would :: be better than 0.0.0.0?

If one runs `wget -qO- https://localhost:3000/` inside the Krill container using `docker exec` when you have set `ip = "0.0.0.0"` you will see that it fails: _(though this may be because on my Docker setup I have `"ipv6": true" set in my `/etc/docker/daemon.json` file)_

```
❯ docker exec krill wget -O- https://localhost:3000/
Connecting to localhost:3000 ([::1]:3000)
wget: can't connect to remote host: Connection refused
```

Trying the localhost IPv4 address instead works:

~/src/krill support-offline-ta*untracked 
❯ docker exec krill wget -O- https://127.0.0.1:3000/
Connecting to 127.0.0.1:3000 (127.0.0.1:3000)
ssl_client: 127.0.0.1: certificate verification failed: self signed certificate
wget: error getting response: Connection reset by peer
```

If one sets `ip = "::"` in `krill.conf` then both work:

```
❯ docker exec krill wget -O- https://localhost:3000/
Connecting to localhost:3000 ([::1]:3000)
ssl_client: localhost: certificate verification failed: self signed certificate
wget: error getting response: Connection reset by peer

~/src/krill support-offline-ta*untracked 
❯ docker exec krill wget -O- https://127.0.0.1:3000/
Connecting to 127.0.0.1:3000 (127.0.0.1:3000)
ssl_client: 127.0.0.1: certificate verification failed: self signed certificate
wget: error getting response: Connection reset by peer
```

You may find other tools that attempt to use IPv6 to connect will similarly fail if you set `ip = "0.0.0.0"` instead of `ip = "::"`.

## Going further

There are still some things to work out here though.

Firstly, if you want to access the testbed user interface from outside the container you'll need to publish the Krill port, e.g. pass `-p 3000:3000` when invoking `docker run`, then you can access the testbed UI at https://localhost:3000/index.html#/testbed on your host.

However, you still need a relying party (RP) such as Routinator, and perhaps also a second Krill instance to act as a child of the testbed, and some way to serve the rsync protocol to the RP (e.g. run rsyncd in another Docker container and share a volume between the Krill container and the rsyncd container so that the files written by Krill can be served, or use `krill-sync` to replicate the files to the container that will serve them), and maybe also an NGINX with a proper certificate, and you need to install the testbed TAL into the RP, etc. How you do this depends on if it is okay to run them all locally on the same host or on multiple VMs or on some sort of cloud container service.

One way to do this is via Docker Compose which can also setup a private network to be used between the containers and ensure container hostnames resolve to the container IP addresses. The Krill end-to-end test (not currently in use because we ran into issues over time with it sometimes being a bit fragile) was Docker Compose based, you can find out more about it here:

- https://github.com/NLnetLabs/rpki-deploy/blob/main/terraform/krill-e2e-test/lib/docker/docker-compose.yml
- https://github.com/NLnetLabs/rpki-deploy/blob/main/terraform/krill-e2e-test/lib/docker/README.md
- https://github.com/NLnetLabs/rpki-deploy/blob/main/terraform/krill-e2e-test/README.md

## Making this easier

I hope this helps understand the issue you encountered, though I appreciate that you still have quite some work ahead of you if you want to create a complete test setup based on Docker and that we haven't published documentation on how to do all of that.

We do have some documentation and blog posts about setting up a test setup as you found, but not from a Docker perspective. We can't really do anything about the Docker knowledge needed but perhaps we could say more about how to do this with Docker.

Ximon

**Comment by ximon18** [comment] 2023-02-15 16:54
Hi @pluschen-stack, 

Can I close this issue?

Thanks,

Ximon

**Comment by pluschen-stack** [comment] 2023-02-15 17:25
Thank you very much for your reply,i have learned a lot about using krill on docker.
I will try to learn krill-e2e-test to know how to build my test enviroment with krill ,routinator ,gobgp.

**Comment by pluschen-stack** [comment] 2023-02-15 17:33
btw,can i use nginx with certificates which created by krill?
it is located in /var/lib/krill/data/ssl/cert.pem and /var/lib/krill/data/ssl/key.pem.

**Comment by pluschen-stack** [comment] 2023-02-15 17:33
> Hi @pluschen-stack,
> 
> Can I close this issue?
> 
> Thanks,
> 
> Ximon
Thank you very much for your reply,i have learned a lot about using krill on docker.
I will try to learn krill-e2e-test to know how to build my test enviroment with krill ,routinator ,gobgp.
btw,can i use nginx with certificates which created by krill?
it is located in /var/lib/krill/data/ssl/cert.pem and /var/lib/krill/data/ssl/key.pem.

**Comment by pluschen-stack** [comment] 2023-02-15 17:36
> Hi @pluschen-stack,
> 
> Can I close this issue?
> 
> Thanks,
> 
> Ximon

Thank you very much for your reply,i have learned a lot about using krill on docker.
I will try krill-e2e-test to know how to build my test enviroment with krill ,routinator ,gobgp.

btw can i use nginx with certificates which is created by krill when it started?
it is located in `/var/lib/krill/data/ssl/key.pem` and `/var/lib/krill/data/ssl/cert.pem`

**Comment by ximon18** [comment] 2023-02-15 17:52
Not: the Krill E2E test hasn't been tested for a while and may not work. It was also created only for our own  use, I pointed to it only as an example to learn from, not because I expect it to be usable as-is.

**Comment by pluschen-stack** [comment] 2023-02-15 18:02
Thank you for your note,i have known it.
Yes,it seems that routinator complain it.
Here is an example which i use self-signed certificate in krill in my virtual machine ubuntu20.04.
```
$ routinator -vvv vrps
[INFO] Using the following TALs:
[INFO]   * ta
[INFO] rsyncing from rsync://testbed.krill.localhost/ta/.
[DEBUG] rsync://testbed.krill.localhost/ta/: Running command Command { std: "rsync" "--contimeout=10" "--max-size=20000000" "-rltz" "--delete" "rsync://testbed.krill.localhost/ta/" "/home/ubuntu/.rpki-cache/repository/rsync/testbed.krill.localhost/ta/", kill_on_drop: false }
[DEBUG] Found valid trust anchor rsync://testbed.krill.localhost/ta/ta.cer. Processing.
[WARN] RRDP https://testbed.krill.localhost/rrdp/notification.xml: error sending request for url (https://testbed.krill.localhost/rrdp/notification.xml): error trying to connect: invalid peer certificate contents: invalid peer certificate: CaUsedAsEndEntity
[INFO] RRDP https://testbed.krill.localhost/rrdp/notification.xml: Update failed and there is no current copy.
[INFO] RRDP https://testbed.krill.localhost/rrdp/notification.xml: Falling back to rsync.
[INFO] rsyncing from rsync://testbed.krill.localhost/repo/.
[DEBUG] rsync://testbed.krill.localhost/repo/: Running command Command { std: "rsync" "--contimeout=10" "--max-size=20000000" "-rltz" "--delete" "rsync://testbed.krill.localhost/repo/" "/home/ubuntu/.rpki-cache/repository/rsync/testbed.krill.localhost/repo/", kill_on_drop: false }
ASN,IP Prefix,Max Length,Trust Anchor
AS65011,10.18.0.0/16,16,ta
```
So this example shows that although rrdp can not run ,but rsync run correctlly as i expected?

**Comment by ximon18** [comment] 2023-02-15 20:14
Looks good to me but really that should be posted as a question at   https://github.com/NLnetLabs/routinator/issues. Not having functional RRDP is not ideal as RRDP is the preferred transport over rsync which is why RPs will try RRDP first and fallback to rsync.

**Comment by ximon18** [comment] 2023-02-15 20:16
I don't think the idea is to put ROAs on the `ta` though, but rather instead to delegate resources to a child CA and create ROAs for that. @timbru?

**Closed** 2023-02-16 12:15 UTC
Labels: docker, documentation
